apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flight-pvc
  labels:
    app: flight
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: efs-sc
