server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: flight
          uri: http://localhost:8082
          predicates:
            - Path=/flights/**, 
        - id: flightreservation
          uri: http://localhost:8083
          predicates:
            - Path=/flightReservations/**, 
        - id: payment
          uri: http://localhost:8084
          predicates:
            - Path=/payments/**, 
        - id: lodging
          uri: http://localhost:8085
          predicates:
            - Path=/lodgings/**, 
        - id: lodgingreservation
          uri: http://localhost:8086
          predicates:
            - Path=/lodgingReservations/**, 
        - id: mypage
          uri: http://localhost:8087
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: flight
          uri: http://flight:8080
          predicates:
            - Path=/flights/**, 
        - id: flightreservation
          uri: http://flightreservation:8080
          predicates:
            - Path=/flightReservations/**, 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**, 
        - id: lodging
          uri: http://lodging:8080
          predicates:
            - Path=/lodgings/**, 
        - id: lodgingreservation
          uri: http://lodgingreservation:8080
          predicates:
            - Path=/lodgingReservations/**, 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
