apiVersion: apps/v1
kind: Deployment
metadata:
  name: lodging
  labels:
    app: lodging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lodging
  template:
    metadata:
      labels:
        app: lodging
    spec:
      containers:
        - name: lodging
          image: "username/lodging:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
